### ISSUE TITLE
Repeat-decade experiments (positive, negative, neutral decades)

### ISSUE THREAD

**Issue by dhruvbhagtani** [dhruvbhagtani/North-Atlantic-Oscillation-tests#2]
Advantages: 
1. Somewhat clear separation between the three phases.

Disadvantages: 
1. Lots of compute, 
2. How do you pick the decades? Can you make them sufficiently different?, 
3. Potential for contamination by other climate modes, 
4. Cannot evaluate temporal evolution, 
5. Can't remove drift (?).

**Comment by dhruvbhagtani** [comment]
I agree with all the disadvantages, plus Andy and Navid's comments about the heat storage. Let's skip this model setup and focus on the other two, since there are a number of choices involved in both of them (particularly in the RYF setup).

**Comment by navidcy** [comment]
Fair, I'm closing this then.
